extends: airbnb-base
plugins:
- import
rules:
  no-console: 0
  arrow-parens: 0
  camelcase: 0
  no-plusplus: 0
  prefer-const: 0
  no-param-reassign: 0
  prefer-promise-reject-errors: 0
  import/no-cycle: 0
